tests/basic: add classic.reset to cleanup to ensure that the env is always clean even if the test fails

diff --git a/tests/main/basic/task.yaml b/tests/main/basic/task.yaml
--- a/tests/main/basic/task.yaml
+++ b/tests/main/basic/task.yaml
@@ -1,5 +1,9 @@
 summary: Check that the classic snap works
 
+restore: |
+    echo "Ensure cleanup even if the test fails"
+    classic.reset || true
+
 execute: |
     echo "Ensure create works"
     classic.create
